python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-99.pt

python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method concat --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method concat --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method concat --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method concat --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method concat --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-99.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method concat --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-99.pt
####################

python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method concat --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-9.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-9.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-9.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-9.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-9.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-9.pt

python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-19.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-19.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-19.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-19.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-19.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-19.pt

python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-29.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-29.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-29.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-29.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-29.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-29.pt

python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-39.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-39.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-39.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-39.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-39.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-39.pt

python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-49.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-49.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-49.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-49.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-49.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-49.pt

python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-59.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-59.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-59.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Normal --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Normal0.1-ends70\epoch-59.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation Acc --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Acc0.1-ends70\epoch-59.pt
python tuning_uniclassifier.py --method CE --modality_type uni --train_modality visual --dataset CREMAD --fusion_method concat --epochs 15 --learning_rate 0.001 --alpha 0.1 --train --num_frame 3 --modulation OGM_GE --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-grad\model-CREMAD-concat-bsz64-lr0.001-epoch150-OGM_GE0.1-ends70\epoch-99.pt

python main_Prototype_grad.py --dataset CREMAD --modulation Proto --fusion_method film --num_frame 3 --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 100 --alpha 3.0 --train --momentum_coef 0.0

python main_CE_test_grad.py --dataset AVE --modulation Normal --fusion_method sum --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad.py --dataset AVE --modulation OGM_GE --fusion_method sum --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad.py --dataset AVE --modulation Acc --fusion_method sum --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3

python main_CE_test_grad.py --dataset AVE --modulation Normal --fusion_method concat --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad.py --dataset AVE --modulation OGM_GE --fusion_method concat --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad.py --dataset AVE --modulation Acc --fusion_method concat --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3

python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-9.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-19.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-29.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-39.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-49.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-59.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 69 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-69.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 79 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-79.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 89 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-89.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method gated --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-99.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-9.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-19.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-29.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-39.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-49.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-59.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 69 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-69.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 79 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-79.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 89 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-89.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method gated --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-gated-bsz64-lr0.001-epoch150-Proto2.0-mon0.0\epoch-99.pt



python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-9.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-19.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-29.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-39.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-49.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-59.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 69 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-69.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 79 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-79.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 89 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-89.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality audio --dataset CREMAD --fusion_method sum --epochs 10 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-99.pt

python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 9 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-9.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 19 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-19.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 29 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-29.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 39 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-39.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 49 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-49.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 59 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-59.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 69 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-69.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 79 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-79.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 89 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-89.pt
python tuning_uniclassifier.py --method CE_Proto --modality_type uni --train_modality visual --dataset CREMAD --fusion_method sum --epochs 15 --learning_rate 0.001 --alpha 2.0 --train --num_frame 3 --modulation Proto --trained_epoch 99 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\Method-CE-Proto-grad\model-CREMAD-sum-bsz64-lr0.001-epoch150-Proto2.0-mon0.0small_data\epoch-99.pt

python main_CE_test_grad_film.py --dataset CREMAD --modulation Normal --fusion_method film --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad_film.py --dataset CREMAD --modulation OGM_GE --fusion_method film --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad_film.py --dataset CREMAD --modulation Acc --fusion_method film --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3

python main_CE_test_grad_film.py --dataset CREMAD --modulation Normal --fusion_method gated --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad_film.py --dataset CREMAD --modulation OGM_GE --fusion_method gated --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad_film.py --dataset CREMAD --modulation Acc --fusion_method gated --epochs 150 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --num_frame 3



python main_unimodality.py --modality audio --dataset CREMAD --batch_size 64 --epochs 130 --num_frame 2 --learning_rate 0.0005 --train
python main_unimodality.py --modality visual --dataset CREMAD --batch_size 64 --epochs 130 --num_frame 2 --learning_rate 0.0005 --train
python main_CE_test_grad.py --dataset CREMAD --modulation Normal --fusion_method sum --epochs 130 --learning_rate 0.0005 --modulation_starts 0 --modulation_ends 50 --alpha 0.1 --train --num_frame 2

python main_CE_test_grad.py --dataset CREMAD --modulation OGM_GE --fusion_method sum --epochs 130 --learning_rate 0.0005 --modulation_starts 0 --modulation_ends 50 --alpha 0.1 --train --num_frame 2
python main_CE_test_grad.py --dataset CREMAD --modulation Acc --fusion_method sum --epochs 130 --learning_rate 0.0005 --modulation_starts 0 --modulation_ends 50 --alpha 0.1 --train --num_frame 2

python main_Prototype_grad.py --dataset CREMAD --modulation Proto --fusion_method sum --num_frame 2 --epochs 130 --learning_rate 0.0005 --modulation_starts 0 --modulation_ends 100 --alpha 5.0 --train --momentum_coef 0.0

python main_CE_test_grad.py --dataset AVE --modulation OGM_GE --fusion_method sum --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_CE_test_grad.py --dataset AVE --modulation OGM_GE --fusion_method sum --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.8 --train --num_frame 4
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method sum --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0

python main_CE_test_grad.py --dataset AVE --modulation OGM_GE --fusion_method sum --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.5 --train --num_frame 4
python main_CE_test_grad_film.py --dataset AVE --modulation Normal --fusion_method concat --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_CE_test_grad_film.py --dataset AVE --modulation Normal --fusion_method film --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_CE_test_grad.py --dataset AVE --modulation Normal --fusion_method gated --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0


python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method film --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method gated --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_CE_test_grad.py --dataset AVE --modulation OGM_GE --fusion_method concat --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_CE_test_grad_film.py --dataset AVE --modulation Normal --fusion_method gated --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_CE_test_grad_film.py --dataset AVE --modulation Normal --fusion_method film --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_CE_test_grad_film.py --dataset AVE --modulation OGM_GE --fusion_method gated --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4
python main_CE_test_grad_film.py --dataset AVE --modulation OGM_GE --fusion_method film --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train --num_frame 4

tuning_comclassifier.py AVE fusion: film, concat

python tuning_comclassifier.py --method CE --dataset AVE --fusion_method film --epochs 30 --learning_rate 0.001 --train --num_frame 4 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\unimodality-audio\model-AVE-bsz64-lr0.001-4\epoch-129.pt --load_path_other D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\unimodality-visual\model-AVE-bsz64-lr0.001-4\epoch-129.pt
python tuning_comclassifier.py --method CE --dataset AVE --fusion_method gated --epochs 30 --learning_rate 0.001 --train --num_frame 4 --load_path D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\unimodality-audio\model-AVE-bsz64-lr0.001-4\epoch-129.pt --load_path_other D:\yunfeng\Multi-modal-Imbalance\ModalityImbalance\ckpt\unimodality-visual\model-AVE-bsz64-lr0.001-4\epoch-129.pt

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method film --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method film --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.5 --train --momentum_coef 0.0 --lr_decay_step 100

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method gated --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method film --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.5
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method film --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.2
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method gated --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method gated --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0


python main_CE_test_grad_film.py --dataset CREMAD --modulation OGM_GE --fusion_method gated --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.1 --train --num_frame 3
python main_CE_test_grad_film.py --dataset CREMAD --modulation OGM_GE --fusion_method film --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.1 --train --num_frame 3
python main_Prototype_grad.py --dataset CREMAD --modulation Proto --fusion_method gated --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 3.0 --train --momentum_coef 0.0

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method gated --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 3.0 --train --momentum_coef 0.0
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method gated --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.5 --train --momentum_coef 0.0

##########
python main_CE_test_grad.py --dataset CGMNIST --modulation Normal --fusion_method concat --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train 
python main_CE_test_grad.py --dataset CGMNIST --modulation OGM_GE --fusion_method concat --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train 
python main_CE_test_grad.py --dataset CGMNIST --modulation OGM_GE --fusion_method sum --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train 

python main_CE_test_grad_film.py --dataset CGMNIST --modulation Normal --fusion_method film --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train 
python main_CE_test_grad_film.py --dataset CGMNIST --modulation OGM_GE --fusion_method film --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train 
python main_CE_test_grad_film.py --dataset CGMNIST --modulation Normal --fusion_method gated --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train 
python main_CE_test_grad_film.py --dataset CGMNIST --modulation OGM_GE --fusion_method gated --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 50 --alpha 0.2 --train 

python main_Prototype_grad.py --dataset CGMNIST --modulation Proto --fusion_method concat --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 60 --alpha 1.0 --train --momentum_coef 0.0
python main_Prototype_grad.py --dataset CGMNIST --modulation Proto --fusion_method gated --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 60 --alpha 1.0 --train --momentum_coef 0.0
python main_Prototype_grad.py --dataset CGMNIST --modulation Proto --fusion_method film --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 60 --alpha 1.0 --train --momentum_coef 0.0

python main_mid_fusion.py --dataset CGMNIST --modulation Normal --fusion_method MMTM --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0

python main_Proto_mid_fusion.py --dataset CGMNIST --modulation Proto --fusion_method MMTM --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0

python main_Prototype_orth.py --dataset CREMAD --modulation Proto --fusion_method sum --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --num_frame 3 --momentum_coef 0.0


python main_Proto_PPO.py --dataset CREMAD --modulation Proto --fusion_method sum --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0

python main_Proto_KL.py --dataset CREMAD --modulation Proto --fusion_method sum --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0


python main_Proto_PPO.py --dataset CREMAD --modulation Proto --fusion_method concat --num_frame 3 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_Proto_PPO.py --dataset CREMAD --modulation Proto --fusion_method film --num_frame 3 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_Proto_PPO.py --dataset CREMAD --modulation Proto --fusion_method gated --num_frame 3 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0

python main_Proto_PPO.py --dataset AVE --modulation Proto --fusion_method sum --num_frame 4 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_Proto_PPO.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_Proto_PPO.py --dataset AVE --modulation Proto --fusion_method film --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0
python main_Proto_PPO.py --dataset AVE --modulation Proto --fusion_method gated --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 1.0 --train --momentum_coef 0.0
python main_Proto_PPO.py --dataset AVE --modulation Proto --fusion_method sum --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0

python main_Proto_PER.py --dataset CREMAD --modulation Proto --fusion_method sum --num_frame 3 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_Proto_PER.py --dataset CREMAD --modulation Proto --fusion_method concat --num_frame 3 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0
python main_Proto_PER.py --dataset CREMAD --modulation Proto --fusion_method film --num_frame 3 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 3.0 --train --momentum_coef 0.0
python main_Proto_PER.py --dataset CREMAD --modulation Proto --fusion_method gated --num_frame 3 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0

#############
python main_Prototype_grad.py --dataset CREMAD --modulation Proto --fusion_method concat --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer AdaGrad
python main_Prototype_grad.py --dataset CREMAD --modulation Normal --fusion_method concat --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer AdaGrad
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer AdaGrad
python main_Prototype_grad.py --dataset AVE --modulation Normal --fusion_method concat --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer AdaGrad

python main_Prototype_grad.py --dataset CREMAD --modulation Proto --fusion_method concat --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer Adam
python main_Prototype_grad.py --dataset CREMAD --modulation Normal --fusion_method concat --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer Adam
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer Adam
python main_Prototype_grad.py --dataset AVE --modulation Normal --fusion_method concat --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer Adam
#################

python main_CE_test_grad.py --dataset CREMAD --modulation Normal --fusion_method concat --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --num_frame 3 --optimizer Adam
python main_Prototype_grad.py --dataset CREMAD --modulation Proto --fusion_method concat --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer Adam
python main_Prototype_grad.py --dataset CREMAD --modulation Proto --fusion_method concat --num_frame 3 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 0.1 --train --momentum_coef 0.0 --optimizer Adam

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer Adam

python main_CE_test_grad.py --dataset AVE --modulation Normal --fusion_method concat --epochs 130 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --num_frame 4 --optimizer AdaGrad

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer AdaGrad
python main_CE_test_grad.py --dataset AVE --modulation Normal --fusion_method concat --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --num_frame 4 --optimizer Adam

python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer Adam
python main_Prototype_grad.py --dataset AVE --modulation Proto --fusion_method concat --num_frame 4 --epochs 100 --learning_rate 0.001 --modulation_starts 0 --modulation_ends 70 --alpha 2.0 --train --momentum_coef 0.0 --optimizer AdaGrad

加上原来方法不好的challenge

introduction： 快速进入模态不均衡问题，

通用性的进一步的好处：继承现有模型结构发展的好处
